version: "3.7"

services:
  work-p:
    image: $IMAGE_NAME
    container_name: work-p
    labels:
      com.qiwa.runtime.product-name: "qiwa"
      com.qiwa.runtime.service-name: "roboagent-spa"
      com.qiwa.runtime.service-vendor: "inspire"
      # com.qiwa.runtime.log-format: "qiwa"
    restart: unless-stopped
    ports:
      - "80:80" #might be deleted if we face an error
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json
    environment:
      VIRTUAL_HOST: robo-agent.$URL
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/index.html || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  default:
    external:
      name: nginx-proxy
